name: high_contrast_override
description: >-
  Example demonstrating how to override high contrast accessibility settings
  using MediaQuery for MaterialApp theme control.

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
